# Generated by Django 4.2 on 2026-05-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_course', models.FloatField(default=0.4)),
                ('w_player_rate', models.FloatField(default=0.35)),
                ('w_motor_rate', models.FloatField(default=0.25)),
                ('race_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RacePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('stadium_code', models.CharField(max_length=2)),
                ('stadium_name', models.CharField(max_length=20)),
                ('race_no', models.IntegerField()),
                ('predicted_boat', models.IntegerField()),
                ('confidence', models.FloatField()),
                ('boats_json', models.TextField(default='[]')),
                ('scores_json', models.TextField(default='{}')),
                ('actual_winner', models.IntegerField(blank=True, null=True)),
                ('hit', models.BooleanField(blank=True, null=True)),
                ('payout', models.IntegerField(blank=True, null=True)),
                ('w_course', models.FloatField()),
                ('w_player_rate', models.FloatField()),
                ('w_motor_rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('date', 'stadium_code', 'race_no')},
            },
        ),
    ]
