# Generated by Django 4.2 on 2026-05-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boat_race', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentweight',
            name='w_local_rate',
            field=models.FloatField(default=0.12),
        ),
        migrations.AddField(
            model_name='agentweight',
            name='w_tenji_st',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='agentweight',
            name='w_tenji_time',
            field=models.FloatField(default=0.13),
        ),
        migrations.AddField(
            model_name='raceprediction',
            name='w_local_rate',
            field=models.FloatField(default=0.12),
        ),
        migrations.AddField(
            model_name='raceprediction',
            name='w_tenji_st',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='raceprediction',
            name='w_tenji_time',
            field=models.FloatField(default=0.13),
        ),
        migrations.AlterField(
            model_name='agentweight',
            name='w_course',
            field=models.FloatField(default=0.3),
        ),
        migrations.AlterField(
            model_name='agentweight',
            name='w_motor_rate',
            field=models.FloatField(default=0.12),
        ),
        migrations.AlterField(
            model_name='agentweight',
            name='w_player_rate',
            field=models.FloatField(default=0.18),
        ),
    ]
